name: joinable_env
channels:
  - pytorch
  - rusty1s
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - torchvision=0.15.0
  - pytorch-lightning
  - torchmetrics
  - matplotlib
  - tqdm
  - networkx
  - scipy
  - igl
  - meshplot
  - pyg
  - pip:
    - pysdf
    - trimesh[easy]    