name: joinable_env
channels:
  - pytorch
  - rusty1s
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - torchvision=0.14.0
  - pytorch-lightning
  - pytorch-geometric
  - torchmetrics
  - matplotlib
  - tqdm
  - networkx
  - scipy
  - igl
  - meshplot
  - pip:
    - pysdf
    - trimesh[easy]    